[package]
name = "rget"
version = "0.0.1"
authors = ["ky <pupupu0701@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.16"
url = "2.1.1"
reqwest = "0.10.7"
anyhow = "1.0"
tokio = { version = "1.0.2", features = ["full"] }
